### ISSUE TITLE
Return code is always 0 - even in case of error

### ISSUE THREAD

**Issue by xurei** [auth0/auth0-deploy-cli#2] opened 2017-01-18 10:37 UTC
When I run a0deploy with a configuration that is incorrect, a0deploy returns 0. It should return an error code instead.

By returning 0 every time, pipelining tools won't stop if the deployment failed.

**Comment by mostekcm** [comment] 2017-01-18 14:01
Great point. Will get this in.

**Comment by mostekcm** [comment] 2017-01-18 20:57
Once I have this PR merged and released, I can merge and release the fix for this: https://github.com/auth0-extensions/auth0-source-control-extension-tools/pull/8

**Comment by mostekcm** [comment] 2017-01-20 18:53
@xurei this is now fixed in version 1.0.4 on npm

**Comment by andreasgrimm** [comment] 2019-02-05 15:02
@mostekcm 	with the current version (2.2.5) it's back: Return code is always 0 - even in case of error.

Is this as intended or should it be able to fail builds etc. ?

**Comment by stevezau** [comment] 2019-02-06 03:32
@andreasgrimm it should return non 0. Can you raise a new issue and ill look into it.

**Closed** 2019-03-15 14:14 UTC
Labels: inprogress

**Comment by adrian-skybaker** [comment] 2020-08-16 21:53
I still see this issue, have opened https://github.com/auth0/auth0-deploy-cli/issues/272
