### ISSUE TITLE
Does not report error for invalid application name in email.json enabled_clients

### ISSUE THREAD

**Issue by max-lancaster** [auth0/auth0-deploy-cli#230] opened 2020-04-29 15:49 UTC
### Description

> Due to renaming a client application we inadvertently had an invalid client name in the `enabled_clients` array of the email.json configuration file which resulted in failure but the `auth0-deploy-cli` still returns status code of 0 (success)

### Reproduction

> Put any invalid client application name in the `enabled_clients` array of email.json

### Environment

- `auth0-deploy-cli` version 4.2.1

This is the error message from the console output:

```
There was an issue deploying to staging. Error: Error: Problem updating connections {"name":"email","id":"con_0qIRI2yxc9erii4g"}
APIError: {"statusCode":400,"error":"Bad Request","message":"Payload validation error: 'Object didn't pass validation for format client-id: Dubs' on property enabled_clients[25] (The client_id of the client to for which the connection is to be enabled).","errorCode":"invalid_body"}
```

**Comment by willvedd** [comment] 2022-02-09 21:31
@max-lancaster thanks for submitting this issue, I can definitely see why it's frustrating. A CLI like this one should definitely return a non-zero to better integrate with CI conventions. I'm closing this because I'm realizing it is a duplicate of #272 but that doesn't mean we're deprioritizing. Please stay tuned with a fix!

**Closed by willvedd** 2022-02-09 21:31 UTC
