### ISSUE TITLE
Keyword replacement problem

### ISSUE THREAD

**Issue by gregorybleiker** [auth0/auth0-deploy-cli#843] opened 2023-08-17 09:42 UTC
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-deploy-cli#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://github.com/auth0/auth0-deploy-cli#documentation) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-deploy-cli/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/auth0-deploy-cli/releases/latest) of this tool and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/tag/auth0-deploy-cli) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

While using v7.18.0 to export the config, with `"AUTH0_PRESERVE_KEYWORDS": true,`, this is not doing anything for our config atm.

We have `config.js` with

```
{
  "AUTH0_DOMAIN": "xxx",
  "AUTH0_CLIENT_ID": "xxx",
  "AUTH0_CLIENT_SECRET": "xxx",
  "AUTH0_KEYWORD_REPLACE_MAPPINGS": {
    "AUDIENCE_GRAPHQL_TEST": "bla.bla.bla",
    ...
```

and `tenant.yaml` with

```
  - name: GraphQL Test
    identifier: ##AUDIENCE_GRAPHQL_TEST##
```

but on export this keyword gets overriden with `bla.bla.bla`. Is there any way to debug the replacement? Our real `config.js` and `tenant.yaml` are much larger in reality, but I don't want to redact all values.

### Expectation

Keywords are preserved

### Reproduction

Seeing this seems to be only the case with our config, this cannot be reproduced without our tenant login. The command we run is: `a0deploy.cmd export --output_folder .\DEV --format yaml -c .\configs\config_dev.json`

### Deploy CLI version

7.18.0

### Node version

18.17.0

**Comment by willvedd** [comment] 2023-11-15 22:29
@gregorybleiker Can you provide more information here? Your issues suggests that keyword preservation doesn't work at all but I can assure you that it does for a wide-array of resources. Admittedly, there are some blindspots, see: #855 . However, it would be useful to see more of your configuration so I can replicate the specific issue.

**Comment by willvedd** [comment] 2023-11-21 14:08
Thanks for opening this issue. I'm going to close this out because I'm unable to troubleshoot with the provided information. It is also possible that its a duplicate of #845 or #855. Please feel empowered to open a new ticket if you ned further assitance!

**Closed** 2023-11-21 14:08 UTC
Labels: bug
