### ISSUE TITLE
v7.6.0: Payload validation error: 'Expected type integer but found type null' on property idle_session_lifetime_in_minutes

### ISSUE THREAD

**Issue by larrydahooster** [auth0/auth0-deploy-cli#465] opened 2022-03-31 10:46 UTC
### Description

_Bad Request: Payload validation error: 'Expected type integer but found type null' on property idle_session_lifetime_in_minutes (Force a user to login after they have been inactive for the specified number (unit: minutes)). (also) Payload validation error: 'Expected type integer but found type null' on property
 session_lifetime_in_minutes (Login session lifetime, how long the session will stay valid (unit: minutes))._

Somehow the dump and deploy functions are incompatible. In my case the dump does not add a "idle_session_lifetime_in_minutes" to my local dumped files. **I assume that the values 'session_lifetime' and 'idle_session_lifetime' do not get exported into the dump when they still have the untouched default values 4320 and 10080. Once I appended one second, the values showed up in the dump.**

### Reproduction

In my case it is a simple dump of my dev environment and a deploy to my staging environment. It is mandatory that the 'session_lifetime' and 'idle_session_lifetime' are untouched, in order to not be exported.

### Environment

> Please provide the following:

- **Version of this library used: 7.6.0**

**Comment by pablotp** [comment] 2022-04-01 09:30
Thanks @larrydahooster for reporting this.
I'm also affected.
- Auth0 configuration as JSON files exported using the a0deploy version 7.5.2
- When importing it with 7.6.0 (without applying any change) it returns the same error message.
For now, I've downgraded to 7.5.2 as workaround.

**Comment by Floppy** [comment] 2022-04-04 11:26
I've got around this by setting the following in my `tenant.json`. The `*_in_minutes` versions suggested by the error message didn't work, looks like it needs to be in hours. 🤷🏻 

```
  "idle_session_lifetime": 72,
  "session_lifetime": 180
```

**Comment by willvedd** [comment] 2022-04-04 17:52
Thanks for opening this. I think the root cause here is folks relying on the default session durations, but somewhere in the Deploy CLI's process, it converts those undefined values to null values that the Management API balks at. Can you folks **confirm that you are/were relying on these default values**?

Both `session_lifetime_in_minutes` and `idle_session_lifetime_in_minutes` are undocumented but supported by the Auth0 Management API when updating those values. On the GET, the values are in hours. There are some legacy use cases where decimal values were used to configure these settings, so the Deploy CLI needs to convert into minutes.

I'm not sure exactly where or why this just started happening but my assumption is that somewhere along the lines of our TS migration, this code was migrated and there may have been very subtle transpilation inconsistencies that would convert the undefined values into null values. Nonetheless, I think I've identified the issue and will have a fix out soon.

**Comment by willvedd** [comment] 2022-04-04 18:02
Also, I'm only able to recreate this for directory (JSON) exports, and not for YAML exports. Can you folks confirm?

**Comment by Floppy** [comment] 2022-04-05 08:58
@willvedd yes, I was relying on the default lifetimes.

**Comment by willvedd** [comment] 2022-04-06 15:45
Fixed in [v7.7.0](https://github.com/auth0/auth0-deploy-cli/releases/tag/v7.7.0). Please update and give it a go!

**Closed by willvedd** 2022-04-06 15:45 UTC
