### ISSUE TITLE
Import fails for Post Change Password (PCP) Hook

### ISSUE THREAD

**Issue by jatinvaidya** [auth0/auth0-deploy-cli#209] opened 2020-02-20 22:29 UTC
### Description

> Please add functionality to import "Post Change Password" (PCP) hook.
> triggerId: `post-change-password`
> https://auth0.com/docs/hooks/extensibility-points/post-change-password
> **Export** of a tenant configuration with the PUCP hook works fine.
> **Import** however, yields the following error 
```
$ a0deploy import -c auth0-prep/config-prep.json -f yaml -i auth0-prep/repo/tenant.yaml 
2020-02-20T22:15:20.691Z - error: Problem running command import
2020-02-20T22:15:20.692Z - error: Schema validation failed loading [
    {
        "keyword": "enum",
        "dataPath": ".hooks[0].triggerId",
        "schemaPath": "#/properties/hooks/items/properties/triggerId/enum",
        "params": {
            "allowedValues": [
                "credentials-exchange",
                "pre-user-registration",
                "post-user-registration"
            ]
        },
        "message": "should be equal to one of the allowed values"
    }
]
```

### Reproduction

1. Create PCP hook on a tenant
2. Export the config using CLI (yaml)
3. Try Importing the config on another tenant.
4. The above-mentioned error is seen.

### Environment

- **Version of this library used:** 
a0deploy 4.0.1

**Comment by shushen** [comment] 2020-03-01 22:57
Duplicate of https://github.com/auth0-extensions/auth0-source-control-extension-tools/issues/85, and being addressed by https://github.com/auth0-extensions/auth0-source-control-extension-tools/pull/88.

**Closed by shushen** 2020-03-01 22:57 UTC
Labels: duplicate

**Comment by pureza** [comment] 2020-03-27 14:09
It looks like this has been fixed 2 weeks ago in `auth0-source-control-extension-tools v4.0.3`. Could you guys make a release with this version, please?
