### ISSUE TITLE
Customization for New Universal Login not written to Auth0

### ISSUE THREAD

**Issue by markus-winkler** [auth0/auth0-deploy-cli#435] opened 2022-03-09 09:27 UTC
**Description**

> We are using the deploy tool to provide our full configuration settings for Auth0 based on our configuration repository which iss stored in GitHub. We are using GitHub Action to realize this:

`
    steps:
      - name: Download files from the current repository
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'
      - name: Install the auth0-deploy-cli
        run: npm install -g auth0-deploy-cli
`
When we use the deploy to to export configuration and later we try to upload it again to Auth0, the branding definitions for Branding / Customization for New Universal Login is not set. When we try to do it manually over Management API, everything works as expected. 

Is this feature already implemented or planned? I know that we are using a Beta-feature of Auth0 and I would expect that this is not implemented right now. 

### Reproduction
This is the output when exporting the current configuration, but it is not possible to upload it:

`branding:
  theme:
    borders:
      button_border_radius: 3
      button_border_weight: 0
      buttons_style: sharp
      input_border_radius: 3
      input_border_weight: 1
      inputs_style: sharp
      show_widget_shadow: true
      widget_border_weight: 0
      widget_corner_radius: 0
    colors:
      body_text: '#000000'
      error: '#E00000'
      header: '#2d333a'
      icons: '#000000'
      input_background: '#ffffff'
      input_border: '#000000'
      input_filled_text: '#000000'
      input_labels_placeholders: '#000000'
      links_focused_components: '#0E1418'
      primary_button: '#D5001C'
      primary_button_label: '#ffffff'
      secondary_button_border: '#0E1418'
      secondary_button_label: '#0E1418'
      success: '#018A16'
      widget_background: '#ffffff'
      widget_border: '#c2c8d0'
    fonts:
      body_text:
        bold: false
        size: 87.5
      buttons_text:
        bold: false
        size: 100
        ...... `

**Comment by markus-winkler** [comment] 2022-03-09 09:28
we also saw that the attributes in export have a different naming as these attributes used by Management API.

**Comment by willvedd** [comment] 2022-03-09 13:36
@markus-winkler Thanks for opening this ticket. Lack of universal login support is a known issue, see: #276. To answer you question about roadmap, yes, it is on our roadmap. Can't make any hard commitment but I'd expect this feature support sometime in the next few week, so please keep your eyes peeled for it!

>we also saw that the attributes in export have a different naming as these attributes used by Management API.

You may see some deviations, but in general this tool closely matches what exists in the API. I invite you to look at the source to confirm that not much transformation is occurring on config dumps.

I'm closing this issue as it's a duplicate of #276 but I invite you to contribute to the conversation there!

**Closed by willvedd** 2022-03-09 13:36 UTC
