### ISSUE TITLE
Allow skipping export of Organizations

### ISSUE THREAD

**Issue by nathanKramer** [auth0/auth0-deploy-cli#427] opened 2022-03-03 01:09 UTC
### Describe the problem you'd like to have solved

Hi, I've recently updated the CLI to version 7, to allow exporting actions.

However, I'm having an issue where our tenant contains thousands of orgs.

The CLI now wants to export them along with their connections, which can't be done in a timely manner, and is not desired for our use-case.

My preference is to treat these Orgs as data, rather than as config that should be exported.
I'm wondering if there is any support for this. 
(or if there are any suggestions for ergonomic work-arounds)

I can't find any evidence that this is supported, but I thought I would ask.

It's not clear to me whether it is safe to try to delete organizations from the resulting export, and then deploy, or if this would delete organizations. (This issue seems relevant: https://github.com/auth0/auth0-deploy-cli/issues/387)

### Describe the ideal solution

Some way to exclude organizations from the export.

e.g, an environment variable, or some kind of manifest that outlines the desired export)

### Attempted work arounds

I tried dropping the `read:organizations` scope, but the export throws:

```
2022-03-03T03:21:01.811Z - info: Retrieving organizations data from Auth0
2022-03-03T03:21:02.012Z - error: Problem running command export during stage load when processing type organizations
2022-03-03T03:21:02.012Z - error: Insufficient scope, expected any of: read:organizations
2022-03-03T03:21:02.013Z - debug: Forbidden: Insufficient scope, expected any of: read:organizations
```

**Comment by willvedd** [comment] 2022-03-08 21:49
Thanks for raising this. I think this is a duplicate of #387 which I have just [merged a relevant fix](https://github.com/auth0/auth0-deploy-cli/pull/388) for. In short, excluding resources from the configuration-as-code files should exclude them from being handled by the deploy CLI. That is, as long as the data doesn't explicitly define those resources as an empty set and rather not defined at all, they should be skipped. I think what you've found is that organizations paired with the YAML format doesn't follow this pattern and that will be fixed in an upcoming release (#434).

But something to remember is that as long as `AUTH0_ALLOW_DELETE` isn't set to true, you're never at risk of deleting any of your organizations. So as far as workarounds go, until 7.5.0 is released, it's ok to remove organization configuration and have `AUTH0_ALLOW_DELETE:false` in your config, you'll just see some warnings.

**Comment by willvedd** [comment] 2022-03-09 13:00
Good news, [7.5.0](https://github.com/auth0/auth0-deploy-cli/releases/tag/v7.5.0) has been released to address this. I encourage you to update and test. I'm closing this for now but please open a new ticket if you're still experiencing this issue.

**Comment by nathanKramer** [comment] 2022-03-09 21:25
@willvedd to be clear - a big part of the issue for us is that the _export_ (as opposed to the deploy) takes an extremely long time.

I don't think that has been addressed. Is it worth keeping this issue open?

**Comment by willvedd** [comment] 2022-03-09 22:04
Ah ok, my mistake! Resource exclusion on the export side is a commonly requested feature that's on our roadmap. We can certainly keep this open until it gets addressed more formally.

**Comment by willvedd** [comment] 2022-03-22 19:02
@nathanKramer I've raised a https://github.com/auth0/auth0-deploy-cli/issues/451 that may solve this issue. It would be great to receive your feedback since your use case would be enhanced by excluding all organizations.

**Comment by willvedd** [comment] 2022-04-08 20:29
As proposed in the [resource exclusion RFC](https://github.com/auth0/auth0-deploy-cli/issues/451), this has been added in the 7.7.0 release. You can bi-directionally exclude all organizations by leveraging the `AUTH0_EXCLUDED` configuration property. Example:

```json
{ 
 "AUTH0_DOMAIN": "<YOUR_DOMAIN>", 
 "AUTH0_CLIENT_ID": "<YOUR_CLIENT_ID>", 
 "AUTH0_CLIENT_SECRET": "<YOUR_CLIENT_SECRET>", 
 "AUTH0_EXCLUDED": [ "organizations"] 
 }

**Closed by willvedd** 2022-04-08 20:29 UTC
Labels: feature request

**Comment by nathanKramer** [comment] 2022-04-12 02:44
Thank you @willvedd!! this looks fantastic
