### ISSUE TITLE
`AUTH0_PRESERVE_KEYWORDS` doesn't work

### ISSUE THREAD

**Issue by Azmah-Bad** [auth0/auth0-deploy-cli#778] opened 2023-04-06 14:25 UTC
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-deploy-cli#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://github.com/auth0/auth0-deploy-cli#documentation) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-deploy-cli/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/auth0-deploy-cli/releases/latest) of this tool and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I installed the latest version of the Auth0 deploy CLI and tried the feature `AUTH0_PRESERVE_KEYWORDS` but the overrides keywords on each export. this was fixed in [here](https://github.com/auth0/auth0-deploy-cli/blob/master/docs/keyword-replacement.md#preserving-keywords-on-export) but it doesn't seem to work.

### Expectation

When running the the command `a0deploy export`, the CLI doesn't overwrite the keywords. 

### Reproduction

1. start an initial export with the flag `AUTH0_PRESERVE_KEYWORDS` as `false` in `config.json` file 
2. replace the values in `tenant.yaml` with the keyword 
3. add keywords to `AUTH0_KEYWORD_REPLACE_MAPPINGS` in `config.json` file
4. set the flag `AUTH0_PRESERVE_KEYWORDS` to `true` in `config.json` file 
5. start an export
6. the keywords gets overwritten

### Deploy CLI version

7.17.1

### Node version

v19.8.1

**Comment by willvedd** [comment] 2023-04-18 20:05
Closing this issue because it doesn't provide any examples or instructions on how to specifically recreate this. Further, I have reason to believe it's a duplicate of #770 .

**Closed by willvedd** 2023-04-18 20:05 UTC
Labels: bug
