### ISSUE TITLE
Where to put prompts settings in directory format?

### ISSUE THREAD

**Issue by pnx472** [auth0/auth0-deploy-cli#768] opened 2023-03-17 10:29 UTC
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-deploy-cli#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [documentation](https://github.com/auth0/auth0-deploy-cli#documentation) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-deploy-cli/issues) and have not found a suitable solution or answer.
- [X] I have upgraded to the [latest version](https://github.com/auth0/auth0-deploy-cli/releases/latest) of this tool and the issue still persists.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Running `a0deploy import` does not import the `identifier_first` and `webauthn_platform_first_factor`.

### Expectation

It should set imported values.

### Reproduction

Run import with values set to true.

promots.json

```json
{
  "universal_login_experience": "new",
  "identifier_first": true,
  "webauthn_platform_first_factor": true
}
```

### Deploy CLI version

7.17.0

### Node version

v16.17.1

**Comment by amandine-perichon** [comment] 2023-03-20 07:14
I'm having the same issue (CLI version 7.17.0, Node v18.12.1).

My prompt configuration is also 
```
{
  "universal_login_experience": "new",
  "identifier_first": true,
  "webauthn_platform_first_factor": false
}
```

I have no custom text settings.

**Comment by poolieweb** [comment] 2023-03-27 12:25
I to can confirm this behaviour. We cant use the CLI tool without manual intervention.
Any update of possbile fix timelines ?

**Comment by willvedd** [comment] 2023-03-28 21:21
Hi folks, this appears to work AFAICT. Make sure to have the `prompts.json` file underneath the `prompts` directory, so like this: `prompts/prompts.json`. Otherwise, the tool won't pick up those settings. Hope that helps! If anyone has any further issues, please provide clear recreation instructions so I can better troubleshoot.

**Comment by pnx472** [comment] 2023-03-29 11:42
Hi @willvedd, we don't move those files around, the title is misleading. We do dump from one tenant and deploy to another one.

The cli states it has been updated but it is not updated with correct values.



1. Dump from tenant with settings on
```
{
  "universal_login_experience": "new",
  "identifier_first": true,
  "webauthn_platform_first_factor": false
}
```
2. Deploy to new tenant
```
2023-03-29T11:27:00.202Z - info: Updated [prompts]: Prompts settings and prompts custom text
```
3. Dump from new tenant
```
{
  "universal_login_experience": "new"
}
```

**Comment by willvedd** [comment] 2023-03-29 15:33
Ok so the actual issue here is that the `identifier_first` and `webauthn_platform_first_factor` properties are set, deploy, but upon subsequent export are not set. This tells me that the Deploy CLI is operating as expected but the Auth0 Management API is not persisting those values for some reason. This sometimes happens due to free-tier limitations, feature flags or codependent configurations not appropriately. In this specific case, I cannot provide any insight, unfortunately. Do you know if any of these apply to your tenant? 

If you're able to, try to hit the `[PATCH /api/v2/prompts](https://auth0.com/docs/api/management/v2#!/Prompts/patch_prompts)` endpoint with the above payload and see if it succeeds. 

And finally, for what its worth, I am unable to recreate this behavior in two test tenants; the configurations apply and are exported as expected.

**Comment by amandine-perichon** [comment] 2023-03-29 20:19
Here is a temporary workaround provided by the Auth0 support. While this is not a fix, this could unblock some of you.

In my case, the issue is caused by a key in tenant.json
"universal_login" is set to {}, and it seems this is unsetting the prompts configuration. 

Workaround:
Update the tenant.json file with "universal_login" set to null, run an import.
Then remove "universal_login" from tenant.json altogether, run an import. For future imports, keep universal_login being removed from the config file.

**Comment by artstupels** [comment] 2023-03-30 09:47
Hello, 

alternatively, you can use the Management API [Update tenant settings](https://auth0.com/docs/api/management/v2#!/Tenants/patch_settings) endpoint, to unset the `universal_login` key.

```
{
    ....,
    "universal_login": null,
    ....
}
```
The issue is not with the Auth0 Deploy CLI, but with the Management API. The prompts configuration is reset, as the **Update tenant settings** call happens after the **Update prompts settings** call in the Auth0 Deploy CLI Script. 

The issue has been reported to the Management API Engineering Team.

**Comment by willvedd** [comment] 2023-07-18 13:47
Folks, I'm still unable to reproduce this issue. And as @artstupels suggests, it may be an issue with the Auth0 Management API rather than the Deploy CLI itself. Can anyone advise if this is still an active issue? If so, I'll follow-up with the appropriate team.

**Comment by willvedd** [comment] 2023-07-24 13:49
Closing this one out because it is not actionable. IMO it's not clear what the exact issue is or if it is an issue at all. Happy to re-open if any further context is provided.

**Closed by willvedd** 2023-07-24 13:49 UTC
Labels: question

**Comment by MattHartz** [comment] 2025-09-25 17:23
Hi @willvedd , I tried a lot of everyone's suggestions here and no luck. If you are available, i can walk you through my configuration. I am able to successfully use the PATCH API, but using the auth0 deploy cli does not work.
