### ISSUE TITLE
Using the deploy cli tool with proxy_url fails when the proxy is presenting it own certificate

### ISSUE THREAD

**Issue by enemarke** [auth0/auth0-deploy-cli#285] opened 2020-11-02 11:33 UTC
I'm unsure it this should be placed as a feature request or as a bug. Please move it if I have placed it wrongly.
I have also posted about it here: https://community.auth0.com/t/using-the-deploy-cli-tool-with-proxy-url-fails-when-the-proxy-is-presenting-it-own-certificate/52566

### Description

When using proxy_url and the proxy is doing ssl-inspection and presenting its own certificate a0deploy fails with:

```
2020-11-02T09:17:16.758Z - debug: Start command export
2020-11-02T09:17:18.226Z - error: Problem running command export
2020-11-02T09:17:18.227Z - error: unable to get local issuer certificate
2020-11-02T09:17:18.228Z - debug: APIError: unable to get local issuer certificate
```

### Reproduction

Use a proxy the replaces the auth0.com certificate with a new certificate signed by the proxy CA and use the a0deploy tool with proxy_url.

### Environment
node --version: v14.15.0
a0deploy.cmd --version: 5.2.1

**Comment by enemarke** [comment] 2020-11-23 11:27
Anyone who can help with this issue?

**Comment by shushen** [comment] 2020-11-30 16:57
Hi, @enemarke,

In order to connect to Auth0 servers in a secured fashion via HTTPS, the clients (including `deploy-cli`) need to be able to validate the server's identity, which is ensured by the server providing a validate and matching CA. Putting in between deploy-cli and the Auth0 server with a proxy with self-signed CA and terminating the TLS connection isn't different from a [MITM attack](https://owasp.org/www-community/attacks/Man-in-the-middle_attack). In order to protect our customers, such intended use will not be support and indeed the described behavior is part of the security measures by design.

Thanks for the report and I'll be closing this issue.

Best regards,
Shu

**Closed by shushen** 2020-11-30 16:57 UTC

**Comment by andrew-wharton** [comment] 2021-12-01 23:42
Since this deploy cli tool is just a Node.js application, and (through a whole chain of libraries building on each other) uses the underlying Node.js APIs for HTTPS calls and certificate validation, you should be able to tell Node to trust the root cert that the proxy CA is using to sign its certificates. You can do this by setting the `NODE_EXTRA_CA_CERTS` environment variable in the shell you're using to run the deploy tool eg.

`$ export NODE_EXTRA_CA_CERTS=[your CA certificate file path]`

See https://stackoverflow.com/questions/29283040/how-to-add-custom-certificate-authority-ca-to-nodejs for more details.
