### ISSUE TITLE
Unable to export / import emailProvider settings

### ISSUE THREAD

**Issue by chronotc** [auth0/auth0-deploy-cli#185] opened 2019-11-27 00:21 UTC
### Description

Currently export command exports everything including credentials for most entities apart from emailProviders.

This is somewhat unexpected considering everything else can be kept in sync using `export` and `import` which is generally recommended when moving to codify auth0 settings.

This behaviour is only documented in `https://github.com/auth0/auth0-deploy-cli/blob/master/src/context/defaults.js` but would be helpful if this is surfaced in the README.md

### Environment

auth0-deploy-cli - v3.6.3

**Comment by jbryson3** [comment] 2020-01-20 16:30
We're also stumbling on this asymmetry. We have our credentials for our `ses` emailProvider checked into our private repo so that `a0deploy import` works as expected.

Typically the workflow for us goes like this:
1. `a0deply export`
2. Discard the changes made to email provider credentials
3. commit any changes as "snapshotting the tenant"
4. Merge feature branch to master
5. 'a0deploy import`

Ideally, getting rid of step #2 would allow for easier automation of the deploy process.

I see a couple of potential solutions:
- Environment/Config variable to opt out of exporting/importing the email providers
- When exporting configurations, do not change the values if set in current config for email provider credentials

**Comment by jbryson3** [comment] 2020-01-20 20:35
After a bit of debugging, I now understand the flaw in my proposed solutions: namely that during `export`, the current `tenant.yaml` file isn't read or used as an input. This means that under the current architecture there is no way to execute an `if` statement where the current `tenant.yaml` is used.

The problem is that there are fields that are essentially "write-only". They are usually sensitive in nature, and cannot be read through the API, but can be used to configure with POSTs or PUTs. I'm not sure how the `export` command should handle these "write-only" keys. I would think they need to be part of the configuration (config.json or tenant.yml) so that `a0deploy import` will work properly, and the values can be updated through the `a0deploy` tool. However, the `export` command has no current knowledge of those keys and can only set some dummy defaults (current behavior).

Paths forward may include:
1. Some intelligent merging of the current `tenant.yaml` and the values retrieved from the tenant calls
    - This seems like a brittle and use case specific solution. I like the simplicity of the current architecture
2. Move the sensitive emailProvider information into the `config.json` to be used in the `defaults.js` when exporting, and can be used as 'overrides' when importing
    - This pollutes the `config.json` a bit with specifics about the emailProviders, especially since the objects are polymorphic in nature (apikey vs accessKeyId/secretAccessKey vs password)

Any other ideas?

**Closed** 2020-05-26 03:28 UTC
